#!/usr/bin/env bash

set -eu

check_required_application() {
  if ! command -v curl; then
    echo "Please install curl before start"
    exit 1
  fi

  if ! command -v zsh; then
    echo "Please install zsh before start"
    exit 1
  fi
}

install_nix() {
  if ! command -v nix; then
    echo "Installing nix..."

    if [[ "$(uname)" == "Linux" ]]; then
      curl -L https://nixos.org/nix/install | sh
    fi

    if [[ "$(uname)" == "Darwin" ]]; then
      sh <(curl -L https://nixos.org/nix/install)
    fi
  fi
}

install_home_manager() {
  # shellcheck disable=SC1090
  source ~/.nix-profile/etc/profile.d/nix.sh

  if ! command -v home-manager; then
    echo "Installing home-manager..."
    export NIX_PATH="$HOME/.nix-defexpr/channels"
    nix-shell '<home-manager>' -A install
  fi
}

install_nix_darwin() {
  if ! command -v darwin-rebuild; then
    echo "Installing nix-darwin..."
    nix-shell '<darwin>' -A installer
    darwin-rebuild switch
  fi
}

add_nix_channel() {
  # shellcheck disable=SC1091
  # shellcheck disable=SC2116

  if [[ "$(uname)" == "Linux" ]]; then
    source "$HOME/.nix-profile/etc/profile.d/nix.sh" # Use unstable channel
  else
    export PATH="$PATH:/run/current-system/sw/bin"
  fi
  nix-channel --add https://nixos.org/channels/nixpkgs-unstable
  nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager

  if [[ "$(uname)" == "Darwin" ]]; then
    nix-channel --add https://github.com/LnL7/nix-darwin/archive/master.tar.gz darwin
  fi

  nix-channel --update
}

populate_nix_config() {
  if [[ "$(uname)" == "Linux" ]]; then
    echo -e "Populating nixpkgs config files for home manager..."
    rm -rf "$HOME/.config/nixpkgs"
    rm -rf "$HOME/.config/home-manager"
    ln -sfn "$PWD"/nixpkgs "$HOME/.config"
    ln -sfn "$PWD/home-manager" "$HOME/.config/home-manager"
  fi

  if [[ "$(uname)" == "Darwin" ]]; then
    echo -e "Populating nixpkgs config files for nix-darwin..."
    rm -rf "$HOME/.nixpkgs"
    rm -rf "$HOME/home-manager"
    ln -sfn "$PWD"/nixpkgs "$HOME/.nixpkgs"
    ln -sfn "$PWD"/home-manager "$HOME/home-manager"
  fi
}

install_tpm() {
  echo "Installing tpm"
  if [ -d ~/.tmux/plugins/tpm ]; then
    rm -rf ~/.tmux/plugins/tpm
  fi
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  export PATH="$HOME/.nix-profile/bin:$PATH"
  zsh -c "$HOME/.tmux/plugins/tpm/bindings/install_plugins"
}

main() {
  install_nix
  add_nix_channel
  populate_nix_config

  if [[ "$(uname)" == "Linux" ]]; then
    install_home_manager
  else
    install_nix_darwin
  fi

  install_tpm

  echo -e "Done!"
}

main
