#!/usr/bin/env bash

set -eu
################################################################################
# Update submodules.
################################################################################
echo -e "Update submodules"
git submodule update --init

################################################################################
# Install brew (for macos)
################################################################################
if ! command -v brew && [[ $(uname) == "Darwin" ]]; then
  echo "Installing brew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

################################################################################
# home-manager
################################################################################
# Install nix; home-manager
if ! command -v nix; then
  echo "Installing nix..."
  curl -L https://nixos.org/nix/install | sh
fi

# Use unstable channel
source "$HOME/.nix-profile/etc/profile.d/nix.sh"
nix-channel --add https://nixos.org/channels/nixpkgs-unstable
nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
nix-channel --update

if ! command -v home-manager; then
  echo "Installing home-manager..."
  nix-shell '<home-manager>' -A install
fi

################################################################################
# Use stow to populate dotfiles
################################################################################
echo -e "Populating config files..."
ln -sf "$PWD"/nixpkgs "$HOME/.config"

echo -e "Setting up with home-manager"
home-manager switch

################################################################################
# Install vim Plug
################################################################################
echo -e "\\nInstalling vim Plug ..."
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install vim plugins and quit
nvim +PlugInstall +qa

########################################
# Install nnn plugins
########################################
curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh

########################################
# Install tpm
########################################
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
echo "Switch to zsh and run below command"
echo "$HOME/tmux/plugins/tpm/bindings/install_plugins"

################################################################################
# DONE
################################################################################
echo -e "Done!"
