#!/usr/bin/env bash

set -eu

################################################################################
# home-manager
################################################################################
# Install nix; home-manager
if ! command -v nix; then
  echo "Installing nix..."
  curl -L https://nixos.org/nix/install | sh
fi

# Use unstable channel
# shellcheck disable=SC1091
source "$HOME/.nix-profile/etc/profile.d/nix.sh"
# shellcheck disable=SC2116
nix-channel --add https://nixos.org/channels/nixpkgs-unstable
nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
nix-channel --update

if ! command -v home-manager; then
  echo "Installing home-manager..."
  nix-shell '<home-manager>' -A install
fi

################################################################################
# Use stow to populate dotfiles
################################################################################
echo -e "Populating nixpkgs config files..."
rm -rf "$HOME/.config/nixpkgs"
ln -sfn "$PWD"/nixpkgs "$HOME/.config"

echo -e "Setting up with home-manager"
home-manager switch

################################################################################
# Install nnn plugins
################################################################################
echo "Installing nnn plugins"
curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh

################################################################################
# tpm
################################################################################
echo "Installing tpm"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
export PATH="$HOME/.nix-profile/bin:$PATH"
zsh -c "$HOME/.tmux/plugins/tpm/bindings/install_plugins"

################################################################################
# DONE
################################################################################
echo -e "Done!"
