local vim_cmd = vim.cmd
local vim_opt = vim.o
local vim_g = vim.g

vim_g.python3_host_prog = "/usr/bin/python3"

vim_opt.autoindent = true
vim_opt.autoread = true
vim_opt.backspace = "indent,eol,start"
vim_opt.backup = false
vim_opt.clipboard = "unnamedplus"
vim_opt.colorcolumn = "80"
vim_opt.cursorcolumn = true
vim_opt.cursorline = true
vim_opt.dir = "/home/bangn/.config/nvim/swap"
vim_opt.encoding = "UTF-8"
vim_opt.expandtab = true
vim_opt.foldenable = false
vim_opt.foldmethod = "indent"
vim_opt.foldnestmax = 10
vim_opt.hlsearch = true
vim_opt.ignorecase = true
vim_opt.incsearch = true
vim_opt.lazyredraw = true
vim_opt.linebreak = true
vim_opt.list = true
vim_opt.listchars = "tab:▷⋅,trail:⋅,nbsp:⋅"
vim_opt.mouse = "c"
vim_opt.number = true
vim_opt.relativenumber = true
vim_opt.ruler = true
vim_opt.scrolloff = 3
vim_opt.shiftwidth = 2
vim_opt.showcmd = true
vim_opt.showmode = false
vim_opt.signcolumn = "yes:1"
vim_opt.smartcase = true
vim_opt.smarttab = true
vim_opt.softtabstop = 4
vim_opt.splitbelow = true
vim_opt.splitright = true
vim_opt.synmaxcol = 120
vim_opt.tabstop = 4
vim_opt.textwidth = 80
vim_opt.ttyfast = true
vim_opt.undodir = "/home/bangn/.config/nvim/undo"
vim_opt.undofile = true
vim_opt.undolevels = 1000
vim_opt.undoreload = 10000
vim_opt.updatetime = 300
vim_opt.wrap = false

vim_cmd("au TermOpen * setlocal nonumber norelativenumber")
