[settings]
experimental = true
python_default_packages_file = "$HOME/.python-default-packages.txt"

[tools]
golang = "latest"
nodejs = "latest"
ruby = "3.3.4"
rust = "latest"
python = "3.10"
uv = "latest"
