[settings]
experimental = true
python_default_packages_file = "$HOME/.python-default-packages.txt"
idiomatic_version_file_enable_tools = []

[tools]
golang = "latest"
nodejs = "latest"
ruby = "3.3.4"
rust = "latest"
python = "latest"
uv = "latest"
